apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: peak6-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: np-peak6
          servicePort: 80
